- name: Install kubectl binary
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  args:
    creates: /usr/local/bin/kubectl
  register: kubectl_install

- name: Verify kubectl version
  shell: kubectl version --client=true
  when: kubectl_install.changed
  register: kubectl_version
  changed_when: false

- name: Show kubectl version
  debug:
    var: kubectl_version.stdout
  when: kubectl_install.changed