# ####################################################################
#
# rke2-create.yaml
#
# Ansible playbook to install RKE2
# Takeover from git: https://github.com/rancherfederal/rke2-ansible
#
# Changes
# 07.04.2025    Thomas Wetzler   Initial file
#
# ####################################################################
---

- name: Install RKE2 for Rancher
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install RKE2
      include_role:
        name: rke2
