---
- name: "Add {{ file_description }} file"  # noqa name[template]
  ansible.builtin.template:
    src: ansible_managed_yaml.j2
    dest: "{{ file_destination }}"
    mode: '0640'
    owner: root
    group: root
  when:
    - file_path | default("") | length != 0
  notify: "Restart {{ service_name }}"

- name: "Remove {{ file_description }} file"  # noqa name[template]
  when:
    - file_path | default("") | length == 0
  block:
    - name: "Check that the {{ file_description }} file exists"  # noqa name[template]
      ansible.builtin.stat:
        path: "{{ file_destination }}"
      register: stat_result

    - name: "Check that the {{ file_description }} config file has ansible managed comments"  # noqa name[template]
      ansible.builtin.lineinfile:
        name: "{{ file_destination }}"
        line: '## This is an Ansible managed file, contents will be overwritten ##'
        state: present
      check_mode: true
      register: ansible_managed_check
      when: stat_result.stat.exists | bool is true

    - name: "Remove the {{ file_description }} file if exists and has ansible managed comments"  # noqa name[template]
      ansible.builtin.file:
        path: "{{ file_destination }}"
        state: absent
      when:
        - ansible_managed_check.changed | bool is false  # noqa no-handler
      notify: "Restart {{ service_name }}"
