---

- name: CIS MODE
  become: true
  when:
    - (cluster_rke2_config.profile | default("") | regex_search('^cis(-\\d+.\\d+)?$')) or
      (group_rke2_config.profile | default("") | regex_search('^cis(-\\d+.\\d+)?$')) or
      (host_rke2_config.profile | default("") | regex_search('^cis(-\\d+.\\d+)?$'))
  block:
    - name: Create etcd group
      ansible.builtin.group:
        name: etcd
        state: present

    - name: Create etcd user
      ansible.builtin.user:
        name: etcd
        comment: etcd user
        shell: /usr/sbin/nologin
        group: etcd
        create_home: false

    - name: Copy systemctl file for kernel hardening for yum installs
      ansible.builtin.copy:
        src: /usr/share/rke2/rke2-cis-sysctl.conf
        dest: /etc/sysctl.d/60-rke2-cis.conf
        remote_src: true
        mode: 0600
      register: sysctl_operation_yum
      when:
        - install_method == "rpm"
      notify:
        - Restart systemd-sysctl
        - "Restart {{ service_name }}"
        - Reboot the machine

    - name: Copy systemctl file for kernel hardening for non-yum installs
      ansible.builtin.copy:
        src: /usr/local/share/rke2/rke2-cis-sysctl.conf
        dest: /etc/sysctl.d/60-rke2-cis.conf
        remote_src: true
        mode: 0600
      register: sysctl_operation_tarball
      when:
        - install_method == "tarball"
      notify:
        - Restart systemd-sysctl
        - "Restart {{ service_name }}"
        - Reboot the machine

    # Per CIS hardening guide, if Kubernetes is already running, making changes to sysctl can result in unexpected
    # side-effects. Rebooting node if RKE2 is already running to prevent potential issues whereas before we were
    # always rebooting, even if the node was brand new and RKE2 not running yet.
    - name: Reboot the machine (Wait for 5 min)
      ansible.builtin.set_fact:
        rke2_reboot: true
      when:
        - (sysctl_operation_yum.changed or sysctl_operation_tarball.changed)
        - rke2_running is defined
        - rke2_running
